ecommercesite/ecommercesite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('products.urls', namespace='products')),
]  + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ecommercesite/products/urls.py
# products/urls.py
from django.urls import path
from . import views

app_name = 'products'  # This should be at the top

urlpatterns = [
    path('', views.product_list, name='product_list'),
    path('<slug:category_slug>/', views.product_list, name='product_list_by_category'),
    path('product/<int:id>/<slug:slug>/', views.product_detail, name="product_detail"),
]

ecommercesite/products/models.py
from django.db import models
from django.urls import reverse


class Category(models.Model):
    name = models.CharField(max_length=250)
    slug = models.SlugField(unique=True)
    
    class Meta:
        verbose_name_plural = "categories"
    
    def __str__(self):
        return self.name
    

class Product(models.Model):
    category = models.ForeignKey(Category, related_name='products', on_delete=models.CASCADE)
    name = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    image = models.ImageField(upload_to='products', blank=True, null=True)
    
    def __str__(self) -> str:
        return self.name
    
    def get_absolute_url(self):
        return reverse('products:product_detail', kwargs={'id':self.id, 'slug':self.slug})
    
    

ecommercesite/products/views.py
from django.shortcuts import render, get_object_or_404
from .models import Category, Product

def product_list(request, category_slug=None):
    category = None
    products = Product.objects.filter(available=True)
    categories = Category.objects.all()
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products = products.filter(category=category)
    
    return render(request, 'products/product/list.html', {
        'category':category,
        'products':products,
        'categories':categories,
    })
    
def product_detail(request, id, slug):
    product = get_object_or_404(Product, id=id, slug=slug, available=True)
    return render(request, 'products/product/detail.html', {'product':product})

ecommercesite/products/templates/products/product/detail.html
{% extends "base.html" %}

{%block title%}{{product.name}}{%endblock%}

{%block content%}
<div class="container mx-auto p-4 flex">

<div>
    {%if product.image%}
    <img src="{{product.image.url}}" alt={{product.name}} class="max-h-[80vh]">
    {%else%}
    <p>The image is not available</p>
    {%endif%}
    <h3 class="font-semibold">{{product.name}}</h3>
    <p>{{product.description}}</p>
    <p class="text-indigo-600">${{product.price}}</p>

    <form action="{%url 'cart:cart_add' product.id%}" method="post" id="add-to-cart-form">
        {% csrf_token %}
        <button type="submit" class="bg-indigo-600 text-white px-4 py-2 rounded">Add to cart</button>
    <p id="message"></p>
    </form>
</div>



</div>

<script>
    document.getElementById('add-to-cart-form').addEventListener("submit", function(event){
        event.preventDefault();

        const form = event.target;
        const url = form.action;
        const formData = new FormData(form);

        fetch(url, {
            method:'POST',
            headers:{
                'X-CSRFToken':formData.get('csrfmiddlewaretoken')
            },
            body: formData
        })
        .then(response => response.json())
        .then(data=>{
            const messageElement = document.getElementById('message');
            if (data.success){
                messageElement.textContent = data.message;
            }else{
                message.textContent = "Failed to add to cart";
            }
        })
        .catch(error=>{
            console.error("Error", error);
        })
    })
</script>
    {%endblock%}

ecommercesite/products/templates/products/product/list.html
{% extends "base.html" %}

{%block title%}My site{%endblock%}

{%block content%}

<div class="container mx-auto p-4 flex">
    <aside class="w-1/4 p-4">
        <h2 class="font-bold">Categories:</h2>
        <ul>
            {%for category in categories%}
            <li>
                <a href="{% url 'products:product_list_by_category' category.slug %}">{{category.name}}</a>
            </li>
            {%endfor%}
            
        </ul>
    </aside>
    <main class="w-3/4 p-4">
        {%if category%}
        <h2 class="font-bold mb-4">{{category.name}}</h2>
        {%else%}
        <h2 class="font-bold mb-4">All Products:</h2>

        {%endif%}
        <div class="grid grid-cols-3 gap-4">
            {% for product in products %}
            <a href="{% url 'products:product_detail' product.id product.slug %}">
            <div>
                {% if product.image %}
                <img src="{{product.image.url}}" alt={{product.name}} class="h-64 w-44 object-cover">
                {%else%}
                <p>The image is not available</p>
                {%endif%}

                <h3 class="font-semibold">{{product.name}}</h3>
                <p>{{product.description}}</p>
                <p class="text-indigo-600">${{product.price}}</p>
            </div>
        </a>
            {%endfor%}

        </div>
    </main>
    
</div>

{%endblock%}

ecommercesite/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}My Super Cool Shop Site{% endblock %}</title>
    {% load static %}
    <link href="{% static 'dist/styles.css' %}" rel="stylesheet">
    <meta name="description" content="Welcome to My Super Cool Shop Site, where you can find the best products at amazing prices!">
    <link rel="icon" href="{% static 'favicon.png' %}">
</head>
<body class="bg-gray-100 text-gray-800 flex flex-col min-h-screen">
    <header class="shadow-md">
        {% include "includes/nav.html" %}
    </header>

    <main class="container mx-auto py-8 flex-grow">
        <h1>Hello World</h1>  <!-- This will display Hello World on your base template -->
        {% block content %}{% endblock %}
    </main>

    <footer>
        <div class="container mx-auto p-4 text-center">
            <p>Footer content here</p>
        </div>
    </footer>
</body>
</html>

ecommercesite/templates/includes/nav.html
<nav class="container mx-auto p-4 flex justify-between items-center">
    <a href='/' class="text-2xl font-bold text-indigo-600">E-Com</a>


    <svg class="w-8" version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
	 width="40px" height="36px" viewBox="0 0 40 36" style="enable-background:new 0 0 40 36;" xml:space="preserve">
<g id="Page-1_4_" sketch:type="MSPage">
	<g id="Desktop_4_" transform="translate(-84.000000, -410.000000)" sketch:type="MSArtboardGroup">
		<path id="Cart" sketch:type="MSShapeGroup" class="st0" d="M94.5,434.6h24.8l4.7-15.7H92.2l-1.3-8.9H84v4.8h3.1l3.7,27.8h0.1
			c0,1.9,1.8,3.4,3.9,3.4c2.2,0,3.9-1.5,3.9-3.4h12.8c0,1.9,1.8,3.4,3.9,3.4c2.2,0,3.9-1.5,3.9-3.4h1.7v-3.9l-25.8-0.1L94.5,434.6"
			/>
	</g>
</g>
  </svg>
</a>
</nav>